#
# GitHub Actions Workflow for pull request events against master
# check for problems in links.
#
# For more information on the actions used in this workflow, please see:
#   https://github.com/actions/checkout
#   https://github.com/marketplace/actions/build-jekyll
#   https://github.com/actions/upload-artifact
#
name: Check links
on:
  pull_request:
    branches: [ master ]

jobs:
  check_links:
    name: Check Markdown links  # TODO: Check also Asciidoc
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check links
        uses: lycheeverse/lychee-action@v1
      - name: Upload report
        uses: actions/upload-artifact@v1
        with:
          name: Markdown error report
          path: /tmp/lychee/out.md
